### ISSUE TITLE
Questions Regarding Problem Set #01 (Particularly Around Relative Path)

### ISSUE THREAD

**Issue by LizzetDRojas** [anyone-can-cook/rclass1#37]
**Question 1**
The biggest issue I had as I worked through problem set was around setting up a relative path (problems 5-6). I placed the rclass1 folder in my OneDrive, so my absolute path looks something like this:

"C:/Users/15622/OneDrive - UCLA IT Services/UCLA SRM/SRM Courses/ED260/rclass1/data" OR
"C:/Users/15622/OneDrive - UCLA IT Services/UCLA SRM/SRM Courses/ED260/rclass1/data/recruiting" (as per when I ran the getwd function)

When I used the setwd() function in the previous problems, I was able to switch working directory from "...rclass1/data" to "rclass1/data/recruiting" in the later problems, so long as I stuck to using absolute path. When I tried to set up a relative path, I was using the ".." for every section between the slashes but that wasn't working (example below), which I'm sure is incorrect but I don't know how to fix it. Does anyone have any advice or can share the code you used if you had similar path?

Code for relative path I used: setwd("../../../../../../../../../recruiting")

***Other Minor Questions***
The other issues I had were regarding how the files download from the ED260A website and GitHub. I was able to manage, but I wanted to pose these questions in case I'm running them incorrectly.
Q2. When I downloaded the intro_to_r.Rmd file, I could only save it as a text file. I worked around this by copying what was in there and pasting it in a New R Notebook on RStudio, which seems to have worked. However, is there a way to be able to save this as a .rmd file right from when I'm accessing this from the website?
Q3. For the .Rdata file from Question 4-6, when I downloaded this from Github, it saved under RGui rather than RStudio (going off of what the little R icon looks like). For the exercises, I was still able to run the code involving this file, so is this okay or again is there a better way to download this?

@lizachavac @briannawright135 @mpatricia01

**Comment by lizachavac** [comment]
@LizzetDRojas it seems like ../ isnt working for you because including ../../ makes your file move up two levels not one. I am including the lecture notes. It can be a bit tricky, but hopefully this helps!
 
![Screen Shot 2021-09-29 at 7 28 02 PM](https://user-images.githubusercontent.com/69886833/135376232-987fa4cf-6574-4978-b499-054547145b1f.png)

Q2. To download the .Rmd files from the lecture you must right click first then click on "save link as". It will automatically save as a .Rmd file. 
Q3. You should've been able to save it in RStudio. Not sure if you are attending office hours, but if you'd like to meet let me know. Brianna has office hours tomorrow as well from 10-11am.

**Comment by LizzetDRojas** [comment]
Thank you! Between your feedback and going to Brianna's office hours, finally figured it out. I appreciate all of your help!
