### ISSUE TITLE
code chunks that download dependencies for knitting lecture .rmd files

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass1#5]
assign: @cyouh95 
copy: @mpatricia01 

looking at the lectures written in fall 2019:

- for some of the earlier lectures, it assumes that whoever is knitting the .rmd file has certain files called within the .rmd (e.g., lecture2_ucla.Rmd refers to fp1.jpj and fp2.jpg)
- for later lectures, we added code at beginning of lecture that would download files that are called within the .rmd (e.g., the beginning of lecture6_ucla.rmd has examples like this)

Tasks for @cyouh95 

- can you modify the lecture for this friday (lectures/intro_to_r/intro_to_r.rmd) to add code chunks that download files called within the .rmd
- you can decide where files like this should be stored on our repo.
- for some files (e.g., data-structures-overview.pnd) we might use those in multiple lectures (e.g., the beamer_header.tex). and we might use them in other courses besides rclass1. keep that in consideration when deciding where such files should be stored on our github repo/organization.

thanks!

**Comment by cyouh95** [comment]
Added the download files/images part to the top of the Rmd. As for where to store those files in the repo, it might make sense to keep them as is (ie. in the `intro_to_r`) folder, since I guess if we were to knit the Rmd, it'll still download those images into that folder. And if we're tracking the images, it'll still be pushed to GitHub inside the `intro_to_r` folder.

But if you want we could still create a designated folder for shared files/images, if that'd be easier to find later! It's just that copies of those files would still exist in the specific lecture folders too.

**Comment by ozanj** [comment]
sounds good!
